/**
 * Writes booking-manifest.csv: every slug in the corpus and whether its page
 * offers online booking.
 *
 * `showBooking` is opt-in — a shop with no entry in src/data/overrides.ts gets
 * no booking — so the off state is nowhere to be seen in the source. This is the
 * audit trail: one committed row per shop, regenerated by prebuild, so a change
 * in who can book shows up as a diff rather than as an absence nobody notices.
 *
 * (Tailwind scans this directory for class names, so prose here avoids words
 * that are also utility names — one such word in a comment adds a rule to the
 * stylesheet that is inlined into all 2216 pages.)
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { OVERRIDES } from '../src/data/overrides.ts';
import raw from '../src/data/barbers.json' with { type: 'json' };

const shops = raw as { slug: string; name: string }[];
const out = fileURLToPath(new URL('../booking-manifest.csv', import.meta.url));

const rows = shops
  .map((s) => ({ slug: s.slug, name: s.name, booking: OVERRIDES[s.slug]?.showBooking === true }))
  .sort((a, b) => a.slug.localeCompare(b.slug));

const csv = ['slug,name,showBooking', ...rows.map((r) => `${r.slug},"${r.name.replace(/"/g, '""')}",${r.booking}`)].join('\n') + '\n';
writeFileSync(out, csv);

const on = rows.filter((r) => r.booking);
console.log(`Booking manifest: ${rows.length} shops, ${on.length} with booking on (${on.map((r) => r.slug).join(', ') || 'none'}), ${rows.length - on.length} off.`);

/** A slug named in overrides that no longer exists in the export would silently do nothing. */
const orphans = Object.keys(OVERRIDES).filter((slug) => !shops.some((s) => s.slug === slug));
if (orphans.length) {
  console.error(`\nsrc/data/overrides.ts names ${orphans.length} slug(s) that are not in barbers.json: ${orphans.join(', ')}\n`);
  process.exit(1);
}
